version: '3'

networks:
  transcendence:
    driver: bridge

services:
  django:
    networks:
      - transcendence
    container_name: django
    build: django
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app/django
    restart: always

  nginx:
    networks:
      - transcendence
    container_name: nginx
    build: nginx
    ports:
      - "443:443"
    volumes:
      - ./django:/app/django
    restart: always
    depends_on:
      - django

volumes:
  django:
    driver_opts:
        type: none
        device: /Users/nayejin/dev/django_tutorial/django
        o: bind